# Generated by Django 5.2.8 on 2026-02-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
