# Generated by Django 6.0.1 on 2026-01-11 07:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, help_text='User biography or description', null=True)),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/')),
                ('student_id', models.CharField(blank=True, help_text='Student ID / Roll Number', max_length=50, null=True)),
                ('batch_year', models.IntegerField(blank=True, help_text='Graduation Year (e.g., 2025)', null=True)),
                ('points', models.IntegerField(default=0, help_text='Gamification points for leaderboard')),
                ('github_username', models.CharField(blank=True, help_text='GitHub username', max_length=100, null=True)),
                ('tech_skills', models.JSONField(blank=True, default=list, help_text="List of technical skills/technologies (e.g., ['Python', 'Django', 'React'])")),
                ('skill_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Developer skill level', max_length=20, null=True)),
                ('portfolio_url', models.URLField(blank=True, help_text='Personal portfolio website', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('provider', models.CharField(blank=True, choices=[('github', 'GitHub'), ('google', 'Google'), ('local', 'Local')], help_text='Authentication provider', max_length=50, null=True)),
                ('provider_id', models.CharField(blank=True, help_text='Unique ID from OAuth provider', max_length=255, null=True)),
                ('github_id', models.CharField(blank=True, help_text='GitHub OAuth user ID', max_length=255, null=True)),
                ('is_member', models.BooleanField(default=False, help_text='Whether user is a club member')),
                ('is_club_admin', models.BooleanField(default=False, help_text='Whether user is a club administrator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['provider', 'provider_id'], name='users_user_provide_f8a100_idx'), models.Index(fields=['github_id'], name='users_user_github__d798fa_idx'), models.Index(fields=['points'], name='users_user_points_d9dafa_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
